spring.application.name=demo
paypal.client.id=AfUxvLdzyrJo8TMaTpICBsOENLg1f0fTfzoPE4SbtucIwVyMzo4_l9Iy9SDAaekvGpCn4uJ4XedxVJV4
paypal.client.secret=EK58rT5Te0cVFFoZ74s2pARNxHDS6hUKH-_Z0ap5Fj9WIfKghK2ZNAzDbvnjHL7xbN1TwpaKY0mtMC2p
paypal.mode=sandbox