spring.application.name=demo
paypal.client.id=ARjsijGcDKAltPeD_iW3GY6j0yXC6utsKVgYKP1Sl2miVNCNTxUKuADbJwFgO0PcuwKl7CMWisplSBiE
paypal.client.secret=ECVUxab4JmVPOZpcj0vTVBASKlbZoBhwU_7k-b9fh91qurSng8Ug3NN_T9_bXgoL8eOJjBSJBmCgtp6w
paypal.mode=sandbox